#!/usr/bin/env bash

set -x
echo "--- rtx Buildkite plugin"

function install_rtx {
  os=linux
  arch=${BUILDKITE_AGENT_META_DATA_AWS_ARCHITECTURE:-amd64}
  url="https://rtx.pub/rtx-latest-${os}-${arch}"
  downloadDir="$(mktemp -d)"
  filename="$(basename $url)"
  tempFilename="$downloadDir/$filename"

  install_path="/usr/local/bin/rtx"

  curl -fLlSso "$tempFilename" "$url"

  sudo mv $tempFilename $install_path
  chmod +x $install_path
  ls -la $install_path

  /usr/local/bin/rtx --version
}

if ! command -v rtx &>/dev/null; then
  echo "Installing rtx"
  install_rtx
fi

echo "Running rtx install"
rtx install -y

